/**
 * Created by Victor on 2017-06-14.
 */
export const RESET = 'TBL/RESETMODEL';
export const ADD_TABLE = 'TBL/ADD_TABLE';
export const UPDATE_TABLE = 'TBL/UPDATE_TABLE';
export const UPDATE_TEXTBOX = 'TBL/UPDATE_TEXTBOX';
export const SELECTED_TEXTBOX = 'TBL/SELECTED_TEXTBOX';
export const REMOVE_TABLE = 'TBL/REMOVE_TABLE';
export const PREVIEW_TABLE = 'TBL/PREVIEW_TABLE';
export const SHOW_PROPERTY = 'TBL/SHOW_PROPERTY';
export const UPDATE_TABLE_PROPERTY = 'TBL/UPDATE_TABLE_PROP';
export const ADD_TABLE_MESSAGE_HEAD = 'TBL/ADD_TABLE_MESSAGE_HEAD';
export const UPDATE_TABLE_MESSAGE_HEAD = 'TBL/UPDATE_TABLE_MESSAGE_HEAD';
export const SET_MESSAGE_HEADORFOOT_TEXTAREA = 'TBL/SET_MESSAGE_HEADORFOOT_TEXTAREA';
export const ADD_TABLE_MESSAGE_FOOT = 'TBL/ADD_TABLE_MESSAGE_FOOT';
export const UPDATE_TABLE_MESSAGE_FOOT = 'TBL/UPDATE_TABLE_MESSAGE_FOOT';
export const UPDATE_REPORT_GROUPS_EXP = 'TBL/UPDATE_REPORT_GROUPS_EXP';